# Generated by Django 5.1.4 on 2025-05-16 06:39

import administracion.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_delete_contactoempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/skrillolhi/_Trabajos/Desarrollo/NODO/NODO-InNexo/administracion'), upload_to=administracion.models.document_upload_path),
        ),
    ]
