# Generated by Django 5.1.4 on 2025-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_alter_documento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='admin_logos/')),
                ('background_theme', models.CharField(choices=[('bg-light', 'Claro'), ('bg-dark', 'Oscuro'), ('bg-sky-light', 'Celeste Claro'), ('bg-sunset-soft', 'Atardecer Suave'), ('bg-forest-deep', 'Bosque Profundo'), ('bg-sandstone-warm', 'Arenisca Cálida'), ('bg-cool-grey', 'Gris Frío'), ('bg-teal-fresh', 'Verde Azulado Fresco')], default='bg-light', max_length=50)),
                ('sidebar_theme', models.CharField(choices=[('bar-darkblue', 'Azul Oscuro'), ('bar-midnight', 'Medianoche'), ('bar-lightgrey', 'Gris Claro'), ('bar-lila-elegant', 'Lila Elegante'), ('bar-gold-warm', 'Dorado Cálido'), ('bar-cyan-vibrant', 'Cyan Vibrante'), ('bar-clean-white', 'Blanco Limpio'), ('bar-maroon-bold', 'Granate Intenso'), ('bar-mint-pastel', 'Menta Pastel')], default='bar-darkblue', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuración del Admin',
                'verbose_name_plural': 'Configuraciones del Admin',
            },
        ),
    ]
