# Generated by Django 5.1.4 on 2025-05-18 06:22

import administracion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_adminconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminconfig',
            options={'verbose_name': 'Configuración del Sitio (Admin y Público)', 'verbose_name_plural': 'Configuraciones del Sitio (Admin y Público)'},
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='public_header_background_color',
            field=models.CharField(default='#ffffff', help_text='Color de fondo del header principal del sitio (ej: #RRGGBB).', max_length=7, verbose_name='Color del Header Público'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='metrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='administracion.metrica'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='background_theme',
            field=models.CharField(choices=[('bg-light', 'Claro'), ('bg-dark', 'Oscuro'), ('bg-sky-light', 'Celeste Claro'), ('bg-sunset-soft', 'Atardecer Suave'), ('bg-forest-deep', 'Bosque Profundo'), ('bg-sandstone-warm', 'Arenisca Cálida'), ('bg-cool-grey', 'Gris Frío'), ('bg-teal-fresh', 'Verde Azulado Fresco')], default='bg-light', help_text='Tema de fondo para el área de contenido del admin.', max_length=50, verbose_name='Tema de Fondo (Admin)'),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal del sitio. Se usa en el panel de administración y en el sitio público.', null=True, upload_to=administracion.models.logo_upload_path),
        ),
        migrations.AlterField(
            model_name='adminconfig',
            name='sidebar_theme',
            field=models.CharField(choices=[('bar-darkblue', 'Azul Oscuro'), ('bar-midnight', 'Medianoche'), ('bar-lightgrey', 'Gris Claro'), ('bar-lila-elegant', 'Lila Elegante'), ('bar-gold-warm', 'Dorado Cálido'), ('bar-cyan-vibrant', 'Cyan Vibrante'), ('bar-clean-white', 'Blanco Limpio'), ('bar-maroon-bold', 'Granate Intenso'), ('bar-mint-pastel', 'Menta Pastel')], default='bar-darkblue', help_text='Tema de color para la barra lateral del admin.', max_length=50, verbose_name='Tema de Barra Lateral (Admin)'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='metrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='administracion.metrica'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='administracion.objetivo'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='administracion.match'),
        ),
    ]
