# Generated by Django 5.1.4 on 2025-05-21 04:32

import administracion.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administracion", "0021_alter_adminconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="archivo",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\vicen\\Documents\\Proyecto Nodo 2\\Nodo-v3\\administracion"
                ),
                upload_to=administracion.models.document_upload_path,
            ),
        ),
    ]
