# Generated by Django 5.1.4 on 2025-05-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_alter_documento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa')),
            ],
        ),
    ]
