"""
Django settings for NODO project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'administracion',
    'home',
    'desafios',
    'iniciativas',
    'autenticacion',
    'blog',
    'storages',
    'django_summernote',
    'sslserver',
    'django_countries',
    "corsheaders",
    'django_extensions',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'NODO.middleware.RestrictAppMiddleware',
]

ROOT_URLCONF = 'NODO.urls'

TEMPLATES = [ 
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'administracion.context_processors.admin_config',
                'home.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'NODO.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME_DEV'),
        'USER':config('DB_USER_DEV'),
        'PASSWORD':config('DB_PASSWORD_DEV'),
        'HOST':config('DB_HOST_DEV'),
        'PORT':config('DB_PORT_DEV'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_URL = f"https://{config('AWS_STORAGE_BUCKET_NAME')}.s3.amazonaws.com/static/"
    STATICFILES_DIRS = []
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Para producción

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



# ... (previous settings) ...

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DOCUMENTS_URL = "/administracion/"  # Documentos accesibles solo en el servidor local
DOCUMENTS_ROOT = os.path.join(BASE_DIR, "administracion")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AWS Settings - Load these regardless of DEBUG
AWS_ACCESS_KEY_ID=config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME') # This must be set correctly in your .env
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME # This will use the bucket name
AWS_S3_FILE_OVERWRITE = False
AWS_S3_SIGNATURE_VERSION = 's3v4' # Corrected: signature_name is s3v4
AWS_S3_REGION_NAME = 'sa-east-1'
AWS_DEFAULT_ACL = None # Or 'public-read' if you want attachments publicly readable
# AWS_S3_VERITY = True # This seems incorrect, perhaps intended for connection verification? Not a standard setting. Remove or check docs.

# Storage Configurations (using the new STORAGES dictionary)
STORAGES = {}

# Media URL and Root
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Local media root for development

if DEBUG:
    # In development, use FileSystemStorage for static and default files
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": os.path.join(BASE_DIR, 'media'),
            },
        },
    }
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
    STATIC_ROOT = None # Not needed for FileSystemStorage when STATICFILES_DIRS is used
else:
    # In production, use S3 for static and default (media) files
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/" # Use S3 URL for statics
    STATICFILES_DIRS = [] # Don't serve static files locally
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build') # Collect static files here before uploading to S3

    STORAGES['staticfiles'] = {
        "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
    }

    STORAGES['default'] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            # Optional: add a location prefix within the bucket for media
            # "location": "media", 
        }
    }
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/" # Use S3 URL for media

# Private documents storage (remains local in both environments)
STORAGES['private_files'] = {
    "BACKEND": "django.core.files.storage.FileSystemStorage",
    "OPTIONS": {
        "location": DOCUMENTS_ROOT,
    }
}


if not DEBUG:
    # Production Database Configuration (assuming you have separate DB creds for prod in .env)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER':config('DB_USER'),
            'PASSWORD':config('DB_PASSWORD'),
            'HOST':config('DB_HOST'),
            'PORT':config('DB_PORT'),
        }
    }

# SSL/Security settings (typically only active in production, but defined always)
SECURE_SSL_REDIRECT = not DEBUG # Only redirect to HTTPS in production
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None # Only if behind a reverse proxy in prod
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Authentication URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/autenticacion/login/'
LOGIN_URL = '/autenticacion/login/'

# Summernote Configuration
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'width': '100%',
    'height': '400px',
    'summernote': {
        'toolbar': [
            ['custom', ['linkToIframe']],
        ],
    },
    'disable_cleaner': False,
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'clear']],
        ['fontname', ['Plus Jakarta Sans', 'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New']],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'linkToIframe']],
        ['view', ['fullscreen', 'codeview', 'help']],
    ],
    'summernote_settings': {
        'codemirror': {
            'lineWrapping': True,
            'mode': 'htmlmixed',
        },
    },
    'cleaner': {
        'allowed_tags': [
            'iframe', 'p', 'br', 'span', 'div', 'b', 'i', 'u', 'ul', 'li', 'ol',
            'a', 'table', 'tr', 'td', 'th', 'thead', 'tbody', 'h1', 'h2', 'h3',
            'h4', 'h5', 'h6', 'img'
        ],
        'allowed_attributes': {
            '*': ['class', 'style', 'id'],
            'a': ['href', 'title', 'target'],
            'img': ['src', 'alt', 'width', 'height'],
            'iframe': ['src', 'frameborder', 'allow', 'allowfullscreen', 'width', 'height'],
        },
        'allowed_styles': ['font-size', 'color', 'background-color', 'text-align'],
    },
    'attachment_filesize_limit': 10 * 1024 * 1024,
    # Set the attachment storage class conditionally based on DEBUG
    'attachment_storage_class': 'django.core.files.storage.FileSystemStorage' if DEBUG else 'storages.backends.s3boto3.S3Boto3Storage'
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "https://127.0.0.1:8000", # This should potentially also be conditional
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_CREDENTIALS = True

METABASE_SESSION_DURATION_MINUTES = config('METABASE_SESSION_DURATION_MINUTES', default=10, cast=int)

# ... (rest of your settings) ...