# Generated by Django 5.1.4 on 2025-05-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_contactoempresa'),
        ('desafios', '0013_alter_desafio_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.contactoempresa'),
        ),
        migrations.AlterField(
            model_name='postulaciondesafio',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.contactoempresa'),
        ),
    ]
